apiVersion: apps/v1
kind: Deployment
metadata:
  name: catcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catcat
  template:
    metadata:
      labels:
        app: catcat
    spec:
      containers:
      - image: okteto.dev/catcat:latest
        name: catcat
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/oneday12345/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "72018d39-f6d6-6162-43bb-5738f6469b70"
        - name: Vless_Path
          value: "/vlmmm"
        - name: Vmess_UUID
          value: "0cadd352-3d8b-312c-843e-a80381fc3cb5"
        - name: Vmess_Path
          value: "/vmlll"
        - name: Share_Path
          value: "/v2link"
